### ISSUE TITLE
过拟合问题

### ISSUE THREAD

**Issue by zhouqunbing** [huaaaliu/RGBX_Semantic_Segmentation#11]
请问在NYU数据集上，数据量是比较少的，而模型采用了四个FRM,四个FFM模块，是如何做到避免模型的过拟合的？
数据增强方面：在Transfoemrs.py文件夹下有很多图像变换方法，但是在Dateloader时候好像并没有全用
dropout的drop_rate为0，
weight_decay=0.01，
请问文章中还用到了什么防止过拟合的方法吗？

**Comment by huaaaliu** [comment]
对于防止过拟合，我们使用了常见的数据增强方式如图像镜像，缩放，随机裁剪等方式，可以参见dataloader.py。对于训练之中防止过拟合，我们保留了segformaer原有的droppath。其中四个ffm frm模块占用网络整体的参数量比例不算太大，因此过拟合的影响不会太大。
