### ISSUE TITLE
S3DIS dataset

### ISSUE THREAD

**Issue by OPradelle** [huaaaliu/RGBX_Semantic_Segmentation#13]
Hi thanks for sharing your work.

I wanted to know how did you generate the 2D ground truth for the S3DIS dataset.
I followed the original procedure from the dataset (https://github.com/alexsax/2D-3D-Semantics/issues/6) but i did not manage to reproduce the score presented in your paper.

Thanks for your answer

**Comment by huaaaliu** [comment]
Hi, thanks for your interest to our work. We does not use some particular methods to generate the 2D ground truth. 
We use the method mentioned in [https://github.com/charlesCXK/Depth2HHA-python](url) to  generate the HHA image, please note the original depth format of the S3DIS and the camera parameters.
Thanks
