### ISSUE TITLE
How to set custom RGB-T datasets sets for training

### ISSUE THREAD

**Issue by 1600337881** [huaaaliu/RGBX_Semantic_Segmentation#14]
Dear Author,I stored the data set as the readme.md, but mine is RGB-T instead of RGB-D.Num_classes,classes_name ,image_size and so on has been modified.But the result of train.py is strange as below.
![QQ图片20221116160600](https://user-images.githubusercontent.com/89259107/202122857-04acc5cc-4bc9-40f3-94bd-cc1a8b869105.png)
![QQ图片20221116160625](https://user-images.githubusercontent.com/89259107/202122939-97e9af04-49f5-47b1-bfa9-c5600e725a43.png)

**Comment by jamycheung** [comment]
Hi @1600337881 ,

thanks for your interest. I would like to help if you can post how you modified the [dataloader](https://github.com/huaaaliu/RGBX_Semantic_Segmentation/blob/main/dataloader/RGBXDataset.py) for your custom RGBT dataset. Besides, please check the [MFNet](https://github.com/haqishen/MFNet-pytorch) dataset which we use in this work as RGBT dataset.
