### ISSUE TITLE
单卡训练的结果？

### ISSUE THREAD

**Issue by kaigelee** [huaaaliu/RGBX_Semantic_Segmentation#15]
请问是否有尝试单卡训练？

**Comment by 1600337881** [comment]
> 

请问怎么设置单卡训练？我修改了engine.py
里的device  default = 0 ，也不行

**Comment by jamycheung** [comment]
Hi @kaigelee, we did not include single-GPU training. But I think you could easily train on single GPU. Please feel free to do that if you are interested in.
Hi @1600337881, you can modify the training script to train on single GPU. For example `CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 train.py -d=0`.

**Comment by kaixin-bai** [comment]
我使用单卡训练达不到论文中多卡训练的精度，请问您有尝试更改哪些配置可以让单卡训练得到的效果更好吗
