### ISSUE TITLE
HHA format

### ISSUE THREAD

**Issue by AmnonDrory** [huaaaliu/RGBX_Semantic_Segmentation#16]
Hi,
Thanks for sharing this great work! I have a question regarding converting data to HHA format. The Depth2HHA-python code writes out the HHA data into .png files, but RGBX seems to be expecting .jpg files, and loads them in COLOR_BGR2RGB mode. What changes need to be made for everything to work correctly?
Thanks!
Amnon Drory

**Comment by jamycheung** [comment]
Hi,

thanks for your interest. We used the HHA format from the SA-Gate [repo](https://github.com/charlesCXK/RGBD_Semantic_Segmentation_PyTorch#nyu-depth-v2). You can also try to download the processed data. Otherwise, you can use Depth2HHA-python code to convert the image.

Best!
