### ISSUE TITLE
How to get the pre-training model？

### ISSUE THREAD

**Issue by White-cat-ed** [huaaaliu/RGBX_Semantic_Segmentation#19]
Hello, I want to ask you how to get the pre-training model, because I found that after the network was rebuilt, the model could not fit well without loading the pre-training model. Thank you

**Comment by elnino9ykl** [comment]
Hi, as described in the readme, you can get the pre-training model here [pre-training segformer](https://drive.google.com/drive/folders/10XgSW8f7ghRs9fJ0dE-EV8G2E_guVsT5?usp=sharing)

Thanks and best,
