### ISSUE TITLE
Scannet Depth inpainting

### ISSUE THREAD

**Issue by OPradelle** [huaaaliu/RGBX_Semantic_Segmentation#20]
Hi, as there is no news from you regarding a previous issue (https://github.com/huaaaliu/RGBX_Semantic_Segmentation/issues/17), i will open a new one.

Looking at the HHA generated images, the repo to generate them use inpainted depth with the raw depth as optional input, but the scannet only provide the raw depth images. Did you first inpaint the depth to fill the empty value or did you directly use the raw depth ?

If it is the case, how did you inpaint them ?

Thanks for your answer.

**Comment by elnino9ykl** [comment]
Hi, 

thank you for your question and interst in our work. You could try simply filling the empty areas with maximum values, which can already help deliver good segmentation results, as shown in our work. Using inpainting methods would further be beneficial.

Best,
