### ISSUE TITLE
is this work accepted by T-PAMI?

### ISSUE THREAD

**Issue by XueZ-phd** [huaaaliu/RGBX_Semantic_Segmentation#23]
Dear Author,

This is a good work to unify the RGB+X segmentation task. I would like to cite this work in my future work, so I wonder if it was accepted?

**Comment by elnino9ykl** [comment]
Hi,
     thank you for your interest. Our work is now under review. You can reference the preprint version:

@article{liu2022cmx,
  title={CMX: Cross-modal fusion for RGB-X semantic segmentation with transformers},
  author={Liu, Huayao and Zhang, Jiaming and Yang, Kailun and Hu, Xinxin and Stiefelhagen, Rainer},
  journal={arXiv preprint arXiv:2203.04838},
  year={2022}
}
