### ISSUE TITLE
How to modify the code of eval.py

### ISSUE THREAD

**Issue by 1600337881** [huaaaliu/RGBX_Semantic_Segmentation#24]
Hi author, your project is very wonderful and I have a small question to ask you.
Not long ago, I used the mmsegmentation, it comes from [OpenMMLab].
Here are the result of eval including mmsegmentation and your project.
![QQ图片20230424070955](https://user-images.githubusercontent.com/89259107/233871139-942b94de-db7d-4b1f-a39b-9f83a73742ea.png)
![QQ图片20230424071033](https://user-images.githubusercontent.com/89259107/233871142-5cebac89-78eb-4928-9742-fd20ac43c732.png)
I wanted to present the eval result in the way of mmsegmentation, please give some advice.

**Comment by jamycheung** [comment]
Hi, about result printing format, you could check and modify the [print_iou](https://github.com/huaaaliu/RGBX_Semantic_Segmentation/blob/main/utils/visualize.py#L54) function regarding your need.
