### ISSUE TITLE
datasets_config

### ISSUE THREAD

**Issue by Chenglong20** [huaaaliu/RGBX_Semantic_Segmentation#25]
I found that the configuration of each dataset is different, can you provide the configuration file of each dataset to facilitate training? Many thanks!

**Comment by Chenglong20** [comment]
当然可以

**Comment by 1600337881** [comment]
我用的仿照VOC格式的配置，NIR，RGB和annotation文件夹，2个txt来设置训练和验证

**Comment by jamycheung** [comment]
Hi, you could check the detailed configuration in [Appendix A](https://arxiv.org/pdf/2203.04838.pdf) of our paper, in which we list all settings for different datasets.
