### ISSUE TITLE
subprocess.CalledProcessError: Command '['/home/he/anconda3/envs/CMX/bin/python', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by CE-AI** [huaaaliu/RGBX_Semantic_Segmentation#26]
When I enter 'CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 train.py' into terminal. The error occurred.

**Comment by jamycheung** [comment]
Hi, please also check the [issue 12](https://github.com/huaaaliu/RGBX_Semantic_Segmentation/issues/12).
