### ISSUE TITLE
Problems with training my own RGB-T data set

### ISSUE THREAD

**Issue by shensongli** [huaaaliu/RGBX_Semantic_Segmentation#30]
Hello, your model is very good, I am trying to use my own RGBT data set to train the model, but I encountered this problem, I found that it may be the opencv version of the problem when I was looking for a solution, so I would like to ask you what version you used in the experiment (my opencv version has met the readme requirements). Or is the problem caused by other factors? Thank you so much for your help!
<img width="760" alt="mmexport1687745558921" src="https://github.com/huaaaliu/RGBX_Semantic_Segmentation/assets/103836676/17ddc100-5bad-4257-bd11-d7df93092e1d">
<img width="760" alt="mmexport1687745561945" src="https://github.com/huaaaliu/RGBX_Semantic_Segmentation/assets/103836676/81fedd49-9fe2-4c18-a586-ce131be99448">

**Comment by jamycheung** [comment]
Duplicated to [#28](https://github.com/huaaaliu/RGBX_Semantic_Segmentation/issues/28).
