### ISSUE TITLE
关于交叉熵损失中设置ignore_index = 255的问题

### ISSUE THREAD

**Issue by 1600337881** [huaaaliu/RGBX_Semantic_Segmentation#31]
训练代码中设置了交叉熵损失函数的ignore_index = 255，发现如果把标签的背景类别像素改成255，会比标签中背景类别像素设置为0（模仿了VOC数据集格式）效果好很多，请问使用rgb-T数据集的话，标签中的背景类别像素值应该设为0还是255？

**Comment by jamycheung** [comment]
Hi, thanks for your interest.
In Table 2, we have included the "Unlabeled" class on RGB-T dataset. You could have a check how your model's performance compared to that.
