### ISSUE TITLE
您好，请问Nyudv2数据集提取之后还做了什么预处理操作吗？

### ISSUE THREAD

**Issue by PinkBunny11** [huaaaliu/RGBX_Semantic_Segmentation#33]
请问Nyudv2数据集提取之后还做了什么预处理操作吗？是否重新进行了对齐？

**Comment by jamycheung** [comment]
Hi thanks for your interest.

We do not have other data pre-processing on the NYU dataset.

**Comment by PinkBunny11** [comment]
好的，非常感谢您!但是我现在复现的时候，已经全部使用了您所给的网络、参数和权重，但是并没有达到您所实现的效果。
就是现在不知道是哪里出现了问题，如果方便的话，可以给我一些建议吗?非常感谢您!～🌹🌹🌹



---原始邮件---
发件人: "Jiaming ***@***.***&gt;
发送时间: 2023年7月15日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huaaaliu/RGBX_Semantic_Segmentation] 您好，请问Nyudv2数据集提取之后还做了什么预处理操作吗？ (Issue #33)




 
Hi thanks for your interest.
 
We do not have other data pre-processing on the NYU dataset.
