### ISSUE TITLE
Issues with training

### ISSUE THREAD

**Issue by ariharasudhanm** [huaaaliu/RGBX_Semantic_Segmentation#34]
When i try to run train.py script I am getting something like this [00:00<?,?it/s]Segmentation fault

Could not sort out the source of the issue.

**Comment by yinbow** [comment]
I have the same issue and fix it when I train the model with a single GPU. Maybe you can train the model with a single GPU to check whether the issue is related to the DDP.

> When i try to run train.py script I am getting something like this [00:00<?,?it/s]Segmentation fault
> 
> Could not sort out the source of the issue.

**Comment by jamycheung** [comment]
Hi, I think this issue is sth. due to the version conflict or issues of cuda and torch version you installed.
