### ISSUE TITLE
Visualizing self- and cross-attention

### ISSUE THREAD

**Issue by madan96** [huaaaliu/RGBX_Semantic_Segmentation#35]
Hi, thanks for the neat implementation! 

I've been trying out RGB-X for a custom dataset and wanted to get a better understanding how the RGB and X modality are contributing to the output mask by visualizing the attention maps for them. I was wondering if you have any suggestions on how to visualize the self- and cross-attention maps for any given input @jamycheung. Thanks!

**Comment by madan96** [comment]
Hi, pinging again on this!

**Comment by jamycheung** [comment]
Hi, thanks for your interest in RGB-X.

Unfortunately, the visualization of attention maps is not included in this work.
But if you want to visualize sth. like **Fig. 6. Visualization of self- and cross-attention** of our previous [MatchFormer paper](https://arxiv.org/pdf/2203.09645.pdf), you could have a look into the [MatchFormer repo](https://github.com/jamycheung/MatchFormer) and the [LoFTR repo](https://github.com/zju3dv/LoFTR). 
I hope this help and also welcome to contribute visualization of RGB-X attention maps.
