### ISSUE TITLE
NYU-Depth v2 performance

### ISSUE THREAD

**Issue by whu-pzhang** [huaaaliu/RGBX_Semantic_Segmentation#36]
@huaaaliu   Hi, Thanks for your Excellent work!

I have try to reproduce the performance of the paper on NYU-Depth-V2 dataset. 

according to instructions,  I use the following command to train:

```
python -m torch.distributed.launch --nproc_per_node=1 train.py -d 0
```

after the 500 epochs finished. I got the mIoU **32.87**, which has a huge gap with **54.1** in the paper. 

Could U give some suggestions？

**Comment by SY-Ch** [comment]
I have the same problem

**Comment by jamycheung** [comment]
Hi @whu-pzhang @SY-Ch @yinbow, thanks for your interest. 

To reproduce the results of NYU-Depth-V2, we recomment to follow the setting which described in the Appendix A. 
For example, in this case we use four 2080 GPUs to train the CMX-B2 model. 
Hope this helps :)
