### ISSUE TITLE
Qusetion about difference map

### ISSUE THREAD

**Issue by LiJiahang617** [huaaaliu/RGBX_Semantic_Segmentation#37]
Hi, thanks for this amazing work!
I'm dealing with related multi-modal detection work. I found your visualization of 'difference map' in your paper. I think it is a very good way to represent the fusion ability. Could you please tell me the details of your difference maps? how is it visualized? Is it just simply subtract or something else? Is there any related code that I could refer to? Is the 'difference map' means the difference between features  before fused and after fused? 
Thanks again for your great work! It would be grateful if you could help me with it.

**Comment by jamycheung** [comment]
Hay there, thanks for your interest. 

The difference map (in Fig. A.1) is only a subtraction between the final prediction and the GT mask. It is not related to the feature map, but this is an interesting point by the way.
