### ISSUE TITLE
关于所提供权重验证精度的问题

### ISSUE THREAD

**Issue by ZZZ1223** [huaaaliu/RGBX_Semantic_Segmentation#40]
我使用https://drive.google.com/file/d/1hlyglGnEB0pnWXfHPtBtCGGlKMDh2K--/view 这里提供的权重文件，去验证NVU-V2，对config文件不进行修改得到的mean_Iou为53.897；和readme里面所说的54.1%有些许差距；之后我修改config里的eval_scale_array和eval_flip得到54.174%的精度；和readme里的54.4%也有些差距。请问所提供的config文件是对应最佳测试结果的吗？感谢。

**Comment by kaixin-bai** [comment]
请问您用b5模型测试的精度能达到论文里的精度吗？

**Comment by ZZZ1223** [comment]
> 请问您用b5模型测试的精度能达到论文里的精度吗？

我没有使用b5测试

**Comment by zichengzichengzi** [comment]
> 我使用https://drive.google.com/file/d/1hlyglGnEB0pnWXfHPtBtCGGlKMDh2K--/view 这里提供的权重文件，去验证NVU-V2，对config文件不进行修改得到的mean_Iou为53.897；和readme里面所说的54.1%有些许差距；之后我修改config里的eval_scale_array和eval_flip得到54.174%的精度；和readme里的54.4%也有些差距。请问所提供的config文件是对应最佳测试结果的吗？感谢。

你好，我想知道训练cmx时数据集要如何准备，我想训练rgbd语义分割，我要将深度图像变成HHA图像并且准备标注后的彩色图像是吗，谢谢

**Comment by 2639292017** [comment]
你好，现在有解决方法了吗
