### ISSUE TITLE
Multispectral Dataset

### ISSUE THREAD

**Issue by aliman80** [huaaaliu/RGBX_Semantic_Segmentation#49]
Hi, Thanks for your wonderful work, May i ask whether we can use your model for multispectral dataset.with no of channels almost 20.

Thanks

**Comment by elnino9ykl** [comment]
Sure, you can also check our CMNeXt model and OAFuser model, which can support multi-channel modalities. Another option is to use a 1x1 convolution layer to first reduce the channels of the specific modality and then input to the CMX model.

CMNeXt: https://github.com/jamycheung/DELIVER
OAFuser: https://github.com/Bryant-Teng/OAFuser
