### ISSUE TITLE
Issues when saving and showing the output img

### ISSUE THREAD

**Issue by ZuoJiaxing** [huaaaliu/RGBX_Semantic_Segmentation#6]
Thanks for your great work and for sharing the code! however, I find it is hard for users to have a try.

First of all, please consider releasing the NYUV2 dataset you are using. It is hard for users to get the same format of data used this repo.

Furthermore, some parts of the code need to be fixed when saving and showing the output img.
When the is enabled, we get the following error:
"RGBX_Semantic_Segmentation/utils/visualize.py", line 7, in set_img_color
    for i in range(0, len(colors)):
TypeError: object of type 'method' has no len()

When the saving is enabled, we can get the following error:
"RGBX_Semantic_Segmentation/eval.py", line 39, in func_per_iteration
    result_img = Image.fromarray(pred.astype(np.uint8), mode='P')
NameError: name 'Image' is not defined

**Comment by huaaaliu** [comment]
Sorry for late response. Thank you for your interest on our work. You can choose download NYUDepth dataset from here: https://github.com/charlesCXK/RGBD_Semantic_Segmentation_PyTorch. However, you may need to generate a .txt list that corresponds the dataloader.
 We are now clear the datasets that are used. The used datasets files may be released later. And sorry for this bug, we did not use the function before. It will be fixed later with the dataset release. We need some time to clean the data and test the codes. Thanks for your understanding.

**Comment by elnino9ykl** [comment]
If there are no more questions, this issue will be closed.
