### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by AI-student-wl** [huaaaliu/RGBX_Semantic_Segmentation#8]
Hello, I will scan the scanet of nyuv2_ After downloading the CMX + segformer-b2.pth model, test the nyuv2 data. I named the model epoch-last.pth and put it in CMX / log_ NYUDepthv2_ mit_ Under the B2 / checkpoint path, the following results are obtained:
![image](https://user-images.githubusercontent.com/72002667/183644195-5f036dce-5000-4e30-bcc4-a02dc76ca9f6.png)
![image](https://user-images.githubusercontent.com/72002667/183644007-48d99ce4-0eee-4f8b-b60b-4336fc1639a9.png)
Can you help me see why? Thank you for your help

**Comment by AI-student-wl** [comment]
Hello, I tested the pre training model of ScanNet and found that the result was very bad. Is it because I can't use weights here
![image](https://user-images.githubusercontent.com/72002667/185334593-5c32c51a-b70e-46c0-b48d-5431b7405e32.png)

**Comment by huaaaliu** [comment]
Hi, sorry for late response. Thanks for your interest on our work. Clearly the weights has not been correctly loaded,which may causes by multiple reasons like mismatching environments or datasets. We still strongly recommended that retraining the network by yourself to get your own model. Alternativ you can load the weights by strictly check all layers.

**Comment by AI-student-wl** [comment]
Thank you for your prompt. I have started to train the model on my own server. The model effect is very good. Thank you again for your excellent work


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huaaaliu/RGBX_Semantic_Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huaaaliu/RGBX_Semantic_Segmentation] 测试结果 (Issue #8)





 
Hi, sorry for late response. Thanks for your interest on our work. Clearly the weights has not been correctly loaded,which may causes by multiple reasons like mismatching environments or datasets. We still strongly recommended that retraining the network by yourself to get your own model. Alternativ you can load the weights by strictly check all layers.
